vich_uploader:
  db_driver: orm

  mappings:
    couvertureFile:
      uri_prefix: /medias/images/
      upload_destination: "%kernel.project_dir%/public/medias/images"
    vignetteFile:
      uri_prefix: /medias/images/
      upload_destination: "%kernel.project_dir%/public/medias/images"
